# Generated by Django 3.1.6 on 2021-03-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('session', models.CharField(max_length=20)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
