# Generated by Django 3.1.6 on 2021-04-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='nid',
            field=models.CharField(default='', max_length=16),
        ),
    ]
